name: Clean jsDelivr Cache

on: 
  # push代码时触发workflow
  push:
    # 忽略README.md
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  jsDelivr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # https://github.com/marketplace/actions/git-changesets
    - id: changed_files
      name: git-changesets
      uses: collin-miller/git-changesets@v0.0.4
      with:
          # Default format is 'csv'. Other valid options are 'space-delimited' and 'json'.
          format: space-delimited

    - name: Install Python
      run: |
          # sudo apt update && \
          sudo apt install python3

    - name: Clean jsDelivr Cache
      run: |
          # echo ${{ steps.changed_files.outputs.all }}
          python clean-jsDelivr-cache.py ${{ github.repository }} ${{ steps.changed_files.outputs.Modified }}
